### ISSUE TITLE
Refactor go-wsman-messages to add Get and Enumerate execution calls (tech debt)

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/go-wsman-messages#102]
Update AMT packages in go-wsman-messages to support parsing responses from AMT into Go struct

- [x] adds execute support for tls [#109 ](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/109)
- [x] adds execute support for remoteaccess [#106 ](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/106)
- [x] adds execute support for userinitiated [#105 ](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/105)
- [x] adds execute support for setup [#104 ](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/104)
- [x] adds execute support for redirection [#103 ](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/103)
- [x] adds execute support for ethernet [#98](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/98)
- [x] adds execute support for publickey [#100](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/100)
- [x] adds execute support for management [#99](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/99)
- [x] adds execute support for environment [#95](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/95)
- [x] adds execute support for authorization [#94](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/94)
- [x] adds execute support for general settings [#86](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/86)
